env:
  browser: true
  es6: true
  jquery: true
  node: true

extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:security/recommended

plugins:
  - node
  - security

root: true

rules:
  security/detect-non-literal-fs-filename: off
  security/detect-object-injection: off

  eqeqeq: error
  no-console: warn
  no-path-concat: error
  no-unused-vars: [error, {argsIgnorePattern: "^_|err|event|next|reject"}]
  no-var: error
  one-var: [error, never]
  prefer-const: error
  quotes: [error, single]
